### PR TITLE
Add grunt build

### PR DESCRIPTION
**Pull request by garyb**
Maintaining the `Makefile` is going to get super annoying I think, using the grunt plugin can make this a whole lot easier it.

I moved the libraries we depend on into `src-lib/` so we can just include the `"src-lib/**/src/**/*.purs", "src-lib/**/src/**/*.purs.hs"` patterns for files in the build, and also this way we don't have to keep adding them to `.gitignore`.

Thoughts? I wasn't sure if we were sticking with the Makefile for some other reason. I guess doing it this way adds another dependency, but we're going to be dependent on the node ecosystem once purescript-in-purescript is done anyway.

### CODE REVIEW

**Comment by joneshf** [comment]
My thought is that we should just go with bower already for our dependencies.

**Comment by garyb** [comment]
Sure, that works too. We'd still benefit from using grunt to run psc.

**Comment by joneshf** [comment]
Agreed.

**Comment by garyb** [comment]
@joneshf good call, if nothing else it's nice to be able to update all the dependencies with just `bower update` now.

**Comment by paf31** [comment]
This is the first time I've used bower or grunt, but this is very cool. We should probably add a section in the README on how to get started though, yes?

I basically just installed `grunt`, `grunt-purescript` and `bower` from `npm` then did `bower update` and `grunt`. Correct?

**Comment by garyb** [comment]
Yeah, good point, and yep that's right for the process. In fact I think the full thing, assuming you just have npm and are in the project directory would be:

```
npm install grunt-cli -g
npm install bower -g
npm install
bower update
grunt
```

The 3rd `npm install` in that list is using the project's `package.json` to download the right version of grunt and associated plugins (like `grunt-purescript`), whereas the `grunt` command is installed by `grunt-cli`.

**Pull request merged**
